---
deployment:
  tasks:
    # SECCIÓN 1: Sincronización de archivos
    - export DEPLOYPATH=/home/contaca3/repositories/erp_sistema/
    - /bin/cp -R * $DEPLOYPATH

    # SECCIÓN 2: Instalación de dependencias (Usando Python 3.12)
    - /home/contaca3/virtualenv/repositories/erp_sistema/3.12/bin/pip install -r requirements.txt

    # SECCIÓN 3: Gestión de Estáticos (Vital para que se vea el CSS)
    - /home/contaca3/virtualenv/repositories/erp_sistema/3.12/bin/python $DEPLOYPATH/manage.py collectstatic --noinput

    # SECCIÓN 4: Base de Datos (MySQL en Producción)
    - /home/contaca3/virtualenv/repositories/erp_sistema/3.12/bin/python $DEPLOYPATH/manage.py migrate --noinput

    # SECCIÓN 5: Reinicio del Servidor
    - touch $DEPLOYPATH/tmp/restart.txt