# Generated by Django 4.2.11 on 2026-04-19 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='Correo de Contacto')),
                ('tipo_contribuyente', models.CharField(choices=[('P', 'Persona'), ('E', 'Empresa')], default='E', max_length=1)),
                ('giro', models.CharField(blank=True, max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('rep_legal_nombre', models.CharField(blank=True, max_length=255)),
                ('rep_legal_rut', models.CharField(blank=True, max_length=12)),
                ('clave_sii', models.CharField(blank=True, max_length=100)),
                ('clave_previred', models.CharField(blank=True, max_length=100)),
                ('clave_unica', models.CharField(blank=True, max_length=100)),
                ('clave_certificado', models.CharField(blank=True, max_length=100)),
                ('honorario_mensual_uf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_renta_anual', models.PositiveIntegerField(default=0)),
                ('tiene_rrhh', models.BooleanField(default=True, verbose_name='¿Módulo RRHH Activo?')),
                ('tiene_contabilidad', models.BooleanField(default=False, verbose_name='¿Módulo Contabilidad Activo?')),
                ('tiene_cobranza', models.BooleanField(default=True, verbose_name='¿Módulo Cobranza Activo?')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador/Contador'), ('cliente', 'Cliente')], default='cliente', max_length=20)),
                ('empresa', models.ForeignKey(blank=True, help_text='Asignar solo si el rol es Cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
