# Generated by Django 4.2.11 on 2026-04-30 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoAccesoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('rrhh', 'Recursos Humanos'), ('contabilidad', 'Contabilidad'), ('cobranza', 'Cobranza')], max_length=30)),
                ('submodulo', models.CharField(blank=True, default='', help_text='Ej: liquidaciones, trabajadores, f29, libro_diario', max_length=60)),
                ('accion', models.CharField(choices=[('ver', 'Ver'), ('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('exportar', 'Exportar'), ('administrar', 'Administrar')], default='ver', max_length=20)),
                ('permitido', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_acceso', to='core.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de acceso de usuario',
                'verbose_name_plural': 'Permisos de acceso de usuarios',
                'unique_together': {('user', 'empresa', 'modulo', 'submodulo', 'accion')},
            },
        ),
    ]
