# Generated by Django 4.2.11 on 2026-08-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_contabilidad_completa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_invergesal',
            field=models.BooleanField(default=False, help_text='Clientes autorizados. Admin y superuser entran siempre.', verbose_name='Puede ver Invergesal'),
        ),
    ]
