# Generated by Django 4.2.11 on 2026-08-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroGastoLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('flete_terrestre', 'Flete Terrestre'), ('servicio_frio', 'Servicio de Frío'), ('despacho', 'Despacho')], max_length=32)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=14)),
            ],
            options={
                'ordering': ['concepto', 'fecha_desde'],
            },
        ),
    ]
