# Generated by Django 4.2.11 on 2026-08-25 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invergesal', '0001_parametros_gasto_liquidacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParametroGastoLiquidacion',
        ),
    ]
