# Generated by Django 4.2.11 on 2026-08-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invergesal', '0002_delete_parametro_gasto_liquidacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaNave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(db_index=True, max_length=16, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('tipo_ais', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tipo_texto', models.CharField(blank=True, max_length=40)),
                ('puerto_previsto', models.CharField(choices=[('SAN ANTONIO', 'San Antonio'), ('VALPARAISO', 'Valparaíso')], db_index=True, max_length=20)),
                ('destino_ais', models.CharField(blank=True, max_length=80)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('rumbo', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('nudos', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('en_zona_puerto', models.BooleanField(default=False)),
                ('visto_en', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Escala de nave',
                'verbose_name_plural': 'Escalas de naves',
                'ordering': ['eta', 'nombre'],
            },
        ),
    ]
