# Generated by Django 5.2.7 on 2025-10-16 00:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tasa_dependiente', models.DecimalField(decimal_places=2, help_text='Ej: 11.44', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Sistema de Salud')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco si es indefinido', null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('plan_salud_pactado', models.DecimalField(decimal_places=2, default=0, help_text='En $ o UF. El sistema debe interpretar.', max_digits=10)),
                ('sueldo_base', models.PositiveIntegerField()),
                ('colacion', models.PositiveIntegerField(default=0)),
                ('movilizacion', models.PositiveIntegerField(default=0)),
                ('tipo_jornada', models.CharField(choices=[('FULL', 'Jornada Completa'), ('PART', 'Jornada Parcial')], default='FULL', max_length=4)),
                ('tipo_gratificacion', models.CharField(choices=[('SIN', 'Sin Gratificación'), ('FIJA', 'Gratificación Fija Mensual'), ('LEGAL', 'Art. 50 (Tope 25% Sueldo Base)')], default='LEGAL', max_length=5)),
                ('afp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.afp')),
                ('sistema_salud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.sistemasalud')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('sueldo_liquido', models.IntegerField(default=0)),
                ('total_haberes', models.IntegerField(default=0)),
                ('total_descuentos', models.IntegerField(default=0)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.contrato')),
            ],
            options={
                'unique_together': {('contrato', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='ItemLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('HABER', 'Haber'), ('DESCUENTO', 'Descuento')], max_length=10)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rrhh.liquidacion')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.PositiveIntegerField()),
                ('numero_cuotas', models.PositiveIntegerField()),
                ('fecha_solicitud', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(default='Chilena', max_length=100)),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('D', 'Divorciado/a'), ('V', 'Viudo/a')], default='S', max_length=1)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email_personal', models.EmailField(max_length=254, unique=True)),
                ('banco', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empresa')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario (Opcional)')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='rrhh.trabajador'),
        ),
    ]
