# Generated by Django 4.2.11 on 2026-04-19 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tasa_dependiente', models.DecimalField(decimal_places=2, help_text='Ej: 11.44', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoNoImponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco si es indefinido', null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('plan_salud_pactado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moneda_plan_salud', models.CharField(choices=[('CLP', '$'), ('UF', 'UF')], default='CLP', max_length=3)),
                ('sueldo_base', models.PositiveIntegerField()),
                ('colacion', models.PositiveIntegerField(default=0, help_text='Haber no imponible')),
                ('movilizacion', models.PositiveIntegerField(default=0, help_text='Haber no imponible')),
                ('tipo_gratificacion', models.CharField(choices=[('SIN', 'Sin Gratificación'), ('FIJA', 'Gratificación Fija Mensual'), ('LEGAL', 'Art. 50 (Tope 25% Sueldo Base)')], default='LEGAL', max_length=5)),
                ('monto_gratificacion_fija', models.PositiveIntegerField(default=0, help_text='Llenar solo si el tipo de gratificación es Fija Mensual')),
                ('tipo_jornada', models.CharField(choices=[('FULL', 'Jornada Completa'), ('PART', 'Jornada Parcial')], default='FULL', max_length=4)),
                ('horas_semanales', models.PositiveIntegerField(default=45)),
                ('dias_semana', models.PositiveIntegerField(default=5)),
                ('afp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.afp')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Sistema de Salud')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(default='Chilena', max_length=100)),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('D', 'Divorciado/a'), ('V', 'Viudo/a')], default='S', max_length=1)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email_personal', models.EmailField(max_length=254, unique=True)),
                ('banco', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario (Opcional)')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.PositiveIntegerField()),
                ('numero_cuotas', models.PositiveIntegerField()),
                ('fecha_solicitud', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('sueldo_liquido', models.IntegerField(default=0)),
                ('total_haberes', models.IntegerField(default=0)),
                ('total_descuentos', models.IntegerField(default=0)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.contrato')),
            ],
            options={
                'unique_together': {('contrato', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='ItemLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('HABER', 'Haber'), ('DESCUENTO', 'Descuento')], max_length=10)),
                ('es_imponible', models.BooleanField(default=True, verbose_name='¿Es imponible?')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rrhh.liquidacion')),
            ],
        ),
        migrations.CreateModel(
            name='ItemContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Bono de Producción, Descuento Farmacia', max_length=100)),
                ('monto', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('HABER', 'Haber'), ('DESCUENTO', 'Descuento')], default='HABER', max_length=10)),
                ('es_imponible', models.BooleanField(default=True, verbose_name='¿Es imponible?')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_recurrentes', to='rrhh.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('uf', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor UF ($)')),
                ('utm', models.PositiveIntegerField(verbose_name='Valor UTM ($)')),
                ('sueldo_minimo', models.PositiveIntegerField(verbose_name='Sueldo Mínimo ($)')),
                ('tope_imponible_afp_uf', models.DecimalField(decimal_places=1, default=81.6, max_digits=5, verbose_name='Tope Imponible AFP (UF)')),
                ('tope_imponible_afp_pesos', models.PositiveIntegerField(verbose_name='Tope Imponible AFP ($)')),
                ('tope_imponible_cesantia_uf', models.DecimalField(decimal_places=1, default=122.6, max_digits=5, verbose_name='Tope Imponible Seguro Cesantía (UF)')),
                ('tope_imponible_cesantia_pesos', models.PositiveIntegerField(verbose_name='Tope Imponible Seguro Cesantía ($)')),
                ('tasa_sis', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tasa SIS (%)')),
                ('asig_familiar_tramo_a_monto', models.PositiveIntegerField(verbose_name='Monto Tramo A')),
                ('asig_familiar_tramo_a_limite', models.PositiveIntegerField(verbose_name='Límite Ingreso Tramo A ($)')),
                ('asig_familiar_tramo_b_monto', models.PositiveIntegerField(verbose_name='Monto Tramo B')),
                ('asig_familiar_tramo_b_limite', models.PositiveIntegerField(verbose_name='Límite Ingreso Tramo B ($)')),
                ('asig_familiar_tramo_c_monto', models.PositiveIntegerField(verbose_name='Monto Tramo C')),
                ('asig_familiar_tramo_c_limite', models.PositiveIntegerField(verbose_name='Límite Ingreso Tramo C ($)')),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='sistema_salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.sistemasalud'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='rrhh.trabajador'),
        ),
        migrations.CreateModel(
            name='RegistroCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('monto_uf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_uf_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pesos', models.PositiveIntegerField(editable=False)),
                ('pagado', models.BooleanField(default=False)),
                ('nro_bh_emitida', models.CharField(blank=True, max_length=50, verbose_name='N° Boleta')),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='core.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'mes', 'ano')},
            },
        ),
    ]
