# Generated by Django 4.2.11 on 2026-04-29 23:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.IntegerField()),
                ('dias_trabajados', models.IntegerField(default=30)),
                ('dias_licencia', models.IntegerField(default=0)),
                ('dias_ausencia', models.IntegerField(default=0)),
                ('horas_extras_50', models.IntegerField(default=0, help_text='Horas extras normales (50%)')),
                ('horas_extras_100', models.IntegerField(default=0, help_text='Horas extras domingos/festivos (100%)')),
                ('bono_esporadico', models.IntegerField(default=0, help_text='Bonos por única vez en este mes ($)')),
                ('descuento_esporadico', models.IntegerField(default=0, help_text='Descuentos por única vez en este mes ($)')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='rrhh.trabajador')),
            ],
            options={
                'verbose_name': 'Novedad Mensual',
                'verbose_name_plural': 'Novedades Mensuales',
                'unique_together': {('trabajador', 'mes', 'ano')},
            },
        ),
    ]
