# Generated by Django 5.2.7 on 2025-10-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='dias_semana',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='contrato',
            name='horas_semanales',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='contrato',
            name='moneda_plan_salud',
            field=models.CharField(choices=[('CLP', '$'), ('UF', 'UF')], default='CLP', max_length=3),
        ),
        migrations.AddField(
            model_name='contrato',
            name='monto_gratificacion_fija',
            field=models.PositiveIntegerField(default=0, help_text='Llenar solo si el tipo de gratificación es Fija Mensual'),
        ),
        migrations.AddField(
            model_name='itemliquidacion',
            name='es_imponible',
            field=models.BooleanField(default=True, verbose_name='¿Es imponible?'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='colacion',
            field=models.PositiveIntegerField(default=0, help_text='Haber no imponible'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='movilizacion',
            field=models.PositiveIntegerField(default=0, help_text='Haber no imponible'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='plan_salud_pactado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
