# Generated by Django 4.2.11 on 2026-04-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_novedadmensual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquidacion',
            old_name='total_descuentos',
            new_name='total_descuentos_legales',
        ),
        migrations.RenameField(
            model_name='liquidacion',
            old_name='total_haberes',
            new_name='total_descuentos_varios',
        ),
        migrations.AddField(
            model_name='indicadoreconomico',
            name='tasa_afp_capital',
            field=models.DecimalField(decimal_places=2, default=11.44, max_digits=5),
        ),
        migrations.AddField(
            model_name='indicadoreconomico',
            name='tasa_afp_cuprum',
            field=models.DecimalField(decimal_places=2, default=11.44, max_digits=5),
        ),
        migrations.AddField(
            model_name='indicadoreconomico',
            name='tasa_afp_habitat',
            field=models.DecimalField(decimal_places=2, default=11.27, max_digits=5),
        ),
        migrations.AddField(
            model_name='indicadoreconomico',
            name='tasa_afp_modelo',
            field=models.DecimalField(decimal_places=2, default=10.58, max_digits=5),
        ),
        migrations.AddField(
            model_name='indicadoreconomico',
            name='tasa_afp_planvital',
            field=models.DecimalField(decimal_places=2, default=11.16, max_digits=5),
        ),
        migrations.AddField(
            model_name='indicadoreconomico',
            name='tasa_afp_provida',
            field=models.DecimalField(decimal_places=2, default=11.45, max_digits=5),
        ),
        migrations.AddField(
            model_name='indicadoreconomico',
            name='tasa_afp_uno',
            field=models.DecimalField(decimal_places=2, default=10.69, max_digits=5),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='afp_nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='afp_tasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='dias_trabajados',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='salud_nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='total_haberes_imponibles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='total_haberes_no_imponibles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='uf_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='utm_valor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
