# Generated by Django 4.2.11 on 2026-04-30 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('rrhh', '0003_rename_total_descuentos_liquidacion_total_descuentos_legales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Comisión por Ventas, Bono por Cumplimiento', max_length=100)),
                ('tipo_calculo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje Fijo sobre una base'), ('TRAMOS', 'Porcentaje Escalonado (Por Tramos de Venta/Base)')], default='PORCENTAJE', max_length=20)),
                ('porcentaje_calculo', models.DecimalField(decimal_places=2, default=0.0, help_text='Usa solo si es Porcentaje Fijo. Ej: 2.5 para 2.5%', max_digits=5)),
                ('es_imponible', models.BooleanField(default=True, verbose_name='¿Es imponible?')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_variables', to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='novedadmensual',
            name='datos_variables',
            field=models.JSONField(blank=True, default=dict, help_text="Almacena bases de cálculo, ej: {'1': 1000000}"),
        ),
        migrations.CreateModel(
            name='TramoConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramo_desde', models.PositiveIntegerField(default=0, verbose_name='Desde ($)')),
                ('tramo_hasta', models.PositiveIntegerField(blank=True, help_text='Dejar en blanco si no tiene límite superior', null=True, verbose_name='Hasta ($)')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa (%)')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='rrhh.conceptovariable')),
            ],
            options={
                'ordering': ['tramo_desde'],
            },
        ),
    ]
