# Generated by Django 4.2.11 on 2026-04-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_conceptovariable_novedadmensual_datos_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='conceptos_variables',
            field=models.ManyToManyField(blank=True, to='rrhh.conceptovariable', verbose_name='Conceptos Variables Aplicables'),
        ),
    ]
