# Generated by Django 5.2.7 on 2025-10-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_conceptonoimponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('uf', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor UF ($)')),
                ('utm', models.PositiveIntegerField(verbose_name='Valor UTM ($)')),
                ('sueldo_minimo', models.PositiveIntegerField(verbose_name='Sueldo Mínimo ($)')),
                ('tope_imponible_afp_uf', models.DecimalField(decimal_places=1, default=81.6, max_digits=5, verbose_name='Tope Imponible AFP (UF)')),
                ('tope_imponible_afp_pesos', models.PositiveIntegerField(verbose_name='Tope Imponible AFP ($)')),
                ('tope_imponible_cesantia_uf', models.DecimalField(decimal_places=1, default=122.6, max_digits=5, verbose_name='Tope Imponible Seguro Cesantía (UF)')),
                ('tope_imponible_cesantia_pesos', models.PositiveIntegerField(verbose_name='Tope Imponible Seguro Cesantía ($)')),
                ('tasa_sis', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tasa SIS (%)')),
                ('asig_familiar_tramo_a_monto', models.PositiveIntegerField(verbose_name='Monto Tramo A')),
                ('asig_familiar_tramo_a_limite', models.PositiveIntegerField(verbose_name='Límite Ingreso Tramo A ($)')),
                ('asig_familiar_tramo_b_monto', models.PositiveIntegerField(verbose_name='Monto Tramo B')),
                ('asig_familiar_tramo_b_limite', models.PositiveIntegerField(verbose_name='Límite Ingreso Tramo B ($)')),
                ('asig_familiar_tramo_c_monto', models.PositiveIntegerField(verbose_name='Monto Tramo C')),
                ('asig_familiar_tramo_c_limite', models.PositiveIntegerField(verbose_name='Límite Ingreso Tramo C ($)')),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
    ]
