# Generated by Django 5.2.7 on 2026-01-21 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_indicadoreconomico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador/Contador'), ('cliente', 'Cliente')], default='cliente', max_length=20)),
                ('empresa', models.ForeignKey(blank=True, help_text='Asignar solo si el rol es Cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
