# Generated by Django 5.2.7 on 2026-01-21 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='clave_certificado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='clave_previred',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='clave_sii',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='clave_unica',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='correo_contacto',
            field=models.EmailField(default=1, max_length=254, verbose_name='Correo de Contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='giro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='honorario_mensual_uf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rep_legal_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rep_legal_rut',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_contribuyente',
            field=models.CharField(choices=[('P', 'Persona'), ('E', 'Empresa')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='empresa',
            name='valor_renta_anual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RegistroCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('monto_uf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_uf_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pesos', models.PositiveIntegerField(editable=False)),
                ('pagado', models.BooleanField(default=False)),
                ('nro_bh_emitida', models.CharField(blank=True, max_length=50, verbose_name='N° Boleta')),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='rrhh.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'mes', 'ano')},
            },
        ),
    ]
