# Generated by Django 4.2.11 on 2026-07-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0012_unificar_previred_por_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='usa_sueldo_minimo',
            field=models.BooleanField(default=False, help_text='Si está activo, el sueldo base se toma del sueldo mínimo vigente en Indicadores económicos.', verbose_name='Usar sueldo mínimo'),
        ),
    ]
