# Generated by Django 4.2.11 on 2026-04-19 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoF29',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código SII')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Código')),
            ],
            options={
                'verbose_name': 'Código F29',
                'verbose_name_plural': 'Diccionario Códigos F29',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='DeclaracionF29',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mes Tributario')),
                ('ano', models.IntegerField(verbose_name='Año Tributario')),
                ('folio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio F29')),
                ('total_a_pagar', models.IntegerField(default=0, verbose_name='Total a Pagar (o Favor)')),
                ('datos_extraidos', models.JSONField(default=dict, verbose_name='Códigos Extraídos')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('verificado', 'Cuadratura Verificada'), ('error', 'Error en Cuadratura')], default='pendiente', max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaraciones_f29', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Declaración F29',
                'verbose_name_plural': 'Declaraciones F29',
                'unique_together': {('empresa', 'mes', 'ano')},
            },
        ),
    ]
