# Generated by Django 4.2.11 on 2026-04-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Cuadratura de IVA a Pagar', max_length=100, verbose_name='Nombre de la Regla')),
                ('codigos_suma', models.CharField(blank=True, help_text='Separados por coma. Ej: 538, 142', max_length=255, verbose_name='Códigos que Suman')),
                ('codigos_resta', models.CharField(blank=True, help_text='Separados por coma. Ej: 539, 062', max_length=255, verbose_name='Códigos que Restan')),
                ('codigo_resultado', models.CharField(help_text='El código que debe coincidir con la operación. Ej: 91', max_length=10, verbose_name='Código Resultado')),
                ('activa', models.BooleanField(default=True, verbose_name='Regla Activa')),
            ],
            options={
                'verbose_name': 'Regla de Validación',
                'verbose_name_plural': 'Reglas de Validación',
            },
        ),
    ]
