# Generated by Django 4.2.11 on 2026-04-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_reglavalidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionf29',
            name='detalles_cuadratura',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Detalles de Cuadratura'),
        ),
    ]
