# Generated by Django 4.2.11 on 2026-04-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('contabilidad', '0003_declaracionf29_detalles_cuadratura'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Asiento')),
                ('glosa', models.CharField(max_length=255, verbose_name='Glosa o Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='core.empresa')),
                ('origen_f29', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_generados', to='contabilidad.declaracionf29', verbose_name='Origen F29')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Libro Diario (Asientos)',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: 1.1.01.01', max_length=20, verbose_name='Código de Cuenta')),
                ('nombre', models.CharField(help_text='Ej: IVA Crédito Fiscal', max_length=150, verbose_name='Nombre de la Cuenta')),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('perdida', 'Resultado Pérdida'), ('ganancia', 'Resultado Ganancia')], max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_contables', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Planes de Cuentas',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PlantillaCentralizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Centralización Compras F29', max_length=100, verbose_name='Nombre de la Plantilla')),
                ('tipo_origen', models.CharField(choices=[('f29', 'Formulario 29 (Simplificada)'), ('rcv', 'Registro de Compra y Ventas (Completa - Próximamente)')], default='f29', max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_centralizacion', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Plantilla de Centralización',
                'verbose_name_plural': 'Plantillas de Centralización',
            },
        ),
        migrations.CreateModel(
            name='LineaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('debe', 'Debe'), ('haber', 'Haber')], max_length=10)),
                ('formula', models.CharField(help_text='Usa códigos entre corchetes. Ej: ([520] / 19) * 100', max_length=255, verbose_name='Fórmula de Cálculo')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cuentacontable')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.plantillacentralizacion')),
            ],
            options={
                'verbose_name': 'Línea de Plantilla',
                'verbose_name_plural': 'Líneas de Plantilla',
            },
        ),
        migrations.CreateModel(
            name='LineaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.BigIntegerField(default=0, verbose_name='Debe')),
                ('haber', models.BigIntegerField(default=0, verbose_name='Haber')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Línea de Asiento',
                'verbose_name_plural': 'Líneas de Asiento',
            },
        ),
    ]
