# Generated by Django 5.2.7 on 2025-10-16 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_contrato_dias_semana_contrato_horas_semanales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Bono de Producción, Descuento Farmacia', max_length=100)),
                ('monto', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('HABER', 'Haber'), ('DESCUENTO', 'Descuento')], default='HABER', max_length=10)),
                ('es_imponible', models.BooleanField(default=True, verbose_name='¿Es imponible?')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_recurrentes', to='rrhh.contrato')),
            ],
        ),
    ]
